export default {
  HOME: '/',
  JOIN: '/join',
  LOGIN: '/login',
  LOGOUT: '/logout',
  SEARCH: '/search',
  CATEGORY: '/category',
  SEARCHITEM: '/search?item=',
  CATEGORYITEM: '/category?item=',
  REPASSWORD: '/re-password',
  NOTICE: '/notice',
  IMGDETAIL: '/img',

  USER: '/user',
  MYEDIT: '/user/edit-profile',
  MYPURCHASE: '/user/purchase',
  MYFAVORITE: '/user/favorite',
  NEWPAYMENT: '/user/payment',
  MYPAYMENT: '/user/paylog',

  MYDASH: '/user/dashboard',
  MYIMGUPLOAD: '/user/upload-image',
  MYUPLOADLIST: '/user/management',
  MYEXCHANGE: '/user/profit',
};
